// PRESERVED: generated by FlutterFire CLI. Firebase Core is not in pubspec.yaml
// and this file is not currently used. Do not delete — it may be re-enabled.
// ignore_for_file: type=lint, uri_does_not_exist, undefined_method, const_initialized_with_non_constant_value
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:aiqr_app/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9XT5kCCbkF-Gwj5O5r9m6O6EcFn-_Wl8',
    appId: '1:57390313191:web:5b88a6fa6421e1e7f07c42',
    messagingSenderId: '57390313191',
    projectId: 'aiqr-a0d91',
    authDomain: 'aiqr-a0d91.firebaseapp.com',
    storageBucket: 'aiqr-a0d91.firebasestorage.app',
    measurementId: 'G-B238BP38HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDspjCR_jcZ03w_jHBybqF2afZ8WoZku_8',
    appId: '1:57390313191:android:d6ca6f77f8402555f07c42',
    messagingSenderId: '57390313191',
    projectId: 'aiqr-a0d91',
    storageBucket: 'aiqr-a0d91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2fzNmBmoADTF4U6zdtkEKO-vlW1DiREg',
    appId: '1:57390313191:ios:73c99d3302e97c77f07c42',
    messagingSenderId: '57390313191',
    projectId: 'aiqr-a0d91',
    storageBucket: 'aiqr-a0d91.firebasestorage.app',
    iosBundleId: 'com.tarurinfotech.aiqr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2fzNmBmoADTF4U6zdtkEKO-vlW1DiREg',
    appId: '1:57390313191:ios:73c99d3302e97c77f07c42',
    messagingSenderId: '57390313191',
    projectId: 'aiqr-a0d91',
    storageBucket: 'aiqr-a0d91.firebasestorage.app',
    iosBundleId: 'com.tarurinfotech.aiqr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9XT5kCCbkF-Gwj5O5r9m6O6EcFn-_Wl8',
    appId: '1:57390313191:web:ed2c3bc174d50f4cf07c42',
    messagingSenderId: '57390313191',
    projectId: 'aiqr-a0d91',
    authDomain: 'aiqr-a0d91.firebaseapp.com',
    storageBucket: 'aiqr-a0d91.firebasestorage.app',
    measurementId: 'G-0RC545J0ET',
  );

}