// PRESERVED: generated by FlutterFire CLI. Firebase Core is not in pubspec.yaml
// and this file is not currently used. Do not delete — it may be re-enabled.
// ignore_for_file: type=lint, uri_does_not_exist, undefined_method, const_initialized_with_non_constant_value
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:aiqr_app/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8G7HvD1wAmfdup5amQ5B4MRNW9eIdXKY',
    appId: '1:316730677708:web:630b5789840a09bf81a569',
    messagingSenderId: '316730677708',
    projectId: 'aiqr-8f37f',
    authDomain: 'aiqr-8f37f.firebaseapp.com',
    storageBucket: 'aiqr-8f37f.firebasestorage.app',
    measurementId: 'G-NEDLYBLXN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkm0Fw5pCfAOqDCisuHLaoCQMszw2iCzg',
    appId: '1:316730677708:android:3c3358e85f906c5f81a569',
    messagingSenderId: '316730677708',
    projectId: 'aiqr-8f37f',
    storageBucket: 'aiqr-8f37f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6AW01AyCGGqp734p6oa4kZ6qLfNkMsoE',
    appId: '1:316730677708:ios:4227939de1c1a57f81a569',
    messagingSenderId: '316730677708',
    projectId: 'aiqr-8f37f',
    storageBucket: 'aiqr-8f37f.firebasestorage.app',
    iosBundleId: 'com.tarurinfotech.aiqr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6AW01AyCGGqp734p6oa4kZ6qLfNkMsoE',
    appId: '1:316730677708:ios:4227939de1c1a57f81a569',
    messagingSenderId: '316730677708',
    projectId: 'aiqr-8f37f',
    storageBucket: 'aiqr-8f37f.firebasestorage.app',
    iosBundleId: 'com.tarurinfotech.aiqr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8G7HvD1wAmfdup5amQ5B4MRNW9eIdXKY',
    appId: '1:316730677708:web:375a9674ed13b16981a569',
    messagingSenderId: '316730677708',
    projectId: 'aiqr-8f37f',
    authDomain: 'aiqr-8f37f.firebaseapp.com',
    storageBucket: 'aiqr-8f37f.firebasestorage.app',
    measurementId: 'G-PRHSQS6DM9',
  );
}
